<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Completed' => 'Completado',
    'Not completed' => 'No completado',
    'The operation was not completed' => 'La operación no fue completada',
    'The operation was completed successfully' => 'La operación se completó exitosamente',
    'Update' => 'Actualizar',
    'Back' => 'Retornar',
];
