<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */

return [
    'Confirmation to load' => 'Confirmación de carga',
    'Execute this action?' => 'Ejexutar esta acción?',
    
    'Confirmation to send' => 'Confirmación de envío',
    'Send data to server?' => 'Enviar datos al servidor?',
    
    'Confirmation to close' => 'Confirmación de cierre',
    'If you close the screen you may lose important information. <br> <br> <strong> Do you want to continue?</strong>' =>
        'Si cierra esta ventana puede perder informacion importante. <br> <br> <strong> Desea continuar?</strong> ',
    
    'Reload this window' => 'Recargar pantalla',
    'This action will return your data to the latest update. <br> <br> <strong> Recent changes will be lost.</strong>' => 
    'Esta acción retornará sus datos a la última actualización. <br> <br> <strong> Los cambios recientes se perderán.</strong>',

    'Ok' => 'Aceptar',
    'Cancel' => 'Cancelar',

    'Delete record' => 'Eliminar registro?',
    'Are you sure to delete this record?' => 'Está seguro de eliminar este registro?',
    'Application not completed' => 'Acción no completada'
];
